name: Specs

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
  schedule:
    - cron: '0 0 * * *'

jobs:
  mysql:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: "mysql"
          MYSQL_DATABASE: marten_auth_test
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    continue-on-error: ${{ matrix.crystal == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        crystal: [
          '1.9.2',
          '1.10.0',
          '1.11.0',
          'nightly',
        ]
    container:
      image: crystallang/crystal:${{ matrix.crystal }}
    steps:
    - uses: actions/checkout@v2
    - name: Install packages required for MySQL
      run: |
        apt-get update
        apt-get -yqq install mysql-client libmysqlclient-dev
    - name: Install shards
      run: shards install --ignore-crystal-version
    - name: Setup env JSON file
      run: cp .spec.env.json.ci .spec.env.json
    - name: Run tests
      run: make tests
      env:
        MARTEN_SPEC_DB_CONNECTION: mysql
  postgresql:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:${{ matrix.db_version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: marten_auth_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    continue-on-error: ${{ matrix.crystal == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        db_version: ['11', '12', '13', '14', '15', 'latest']
        crystal: [
          '1.9.2',
          '1.10.0',
          '1.11.0',
          'nightly',
        ]
    container:
      image: crystallang/crystal:${{ matrix.crystal }}
    steps:
    - uses: actions/checkout@v2
    - name: Install packages required for PostgreSQL
      run: |
        apt-get update
        apt-get -yqq install libpq-dev postgresql-client libsqlite3-dev
    - name: Install shards
      run: shards install --ignore-crystal-version
    - name: Setup env JSON file
      run: cp .spec.env.json.ci .spec.env.json
    - name: Run tests
      run: make tests
      env:
        MARTEN_SPEC_DB_CONNECTION: postgresql
  sqlite:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.crystal == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        crystal: [
          '1.9.2',
          '1.10.0',
          '1.11.0',
          'nightly',
        ]
    container:
      image: crystallang/crystal:${{ matrix.crystal }}
    steps:
    - uses: actions/checkout@v2
    - name: Install packages required for SQLite
      run: |
        apt-get update
        apt-get -yqq install libsqlite3-dev
    - name: Install shards
      run: shards install --ignore-crystal-version
    - name: Setup env JSON file
      run: cp .spec.env.json.ci .spec.env.json
    - name: Run tests
      run: make tests
